### PR TITLE
Closes #68

### LINKED ISSUE #68: The WMS Client test does not put "Perform GetMap request for all the layers" on passed when all child tests have been passed
I executed the WMS Client test in combination with our desktop WMS client software based on LuciadLightspeed. It works and it seems all child tests have been passed, but the "Perform GetMap request for all the layers"  parent node seems to remain on the failed state.

Here is a screenshot of the test result:

image

As you can see, all tests below "Perform GetMap request for all the layers" are passed, but the parent node remains failed. I can consistently reproduce this.

### PR DESCRIPTION
**Pull request by bpross-52n**
Closes #68

### CODE REVIEW

**Review by dstenger — APPROVED** [review]

**Review by dstenger — CHANGES_REQUESTED** [review]
The interactive test result page is working correct now.
However, when you stop the tests and view the test results, the status of the tests is not displayed correctly in the tree.

**Comment by dstenger** [comment]
Please see screenshot for further details:

Bildschirmfoto vom 2024-04-18 10-17-59

**Comment by dstenger** [comment]
Also, when I executed the GetFeatureInfo test, following StackTrace was logged (same message around 16 times):

```
a39b6e> Apr 18, 2024 8:15:32 AM org.apache.catalina.core.StandardWrapperValve invoke
a39b6e> SEVERE: Servlet.service() for servlet [TestSuiteController] in context with path [/teamengine] threw exception [org.xml.sax.SAXParseException; Premature end of file.] with root cause
a39b6e> org.xml.sax.SAXParseException; Premature end of file.
a39b6e> 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
a39b6e> 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
a39b6e> 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
a39b6e> 	at com.occamlab.te.spi.jaxrs.resources.wmsclient.TestMapResources.handleGet(TestMapResources.java:79)
a39b6e> 	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
a39b6e> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
a39b6e> 	at java.lang.reflect.Method.invoke(Method.java:498)
a39b6e> 	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
...
```

**Comment by bpross-52n** [comment]
https://github.com/opengeospatial/ets-wms-client13/commit/fde3a02fba86df6c8e9dca3c0323a47d681d891c removed the autos and building_centers layers from the tests. There were still some leftovers from. Also, the teamengine needs to be updated to reflect the reduced number of tested layers. See https://github.com/opengeospatial/ets-wms-client13/issues/32 and https://github.com/opengeospatial/teamengine/commit/d9291d45ea65d4934350e8b585495c2ed562e628

**Review by dstenger — APPROVED** [review]

**Pull request merged**
